---
##
# Nodejs, gettext and npm packages
##
- name: install nodejs and gettext
  apt: pkg=nodejs state=installed update-cache=yes
  with_items:
    - gettext
  run_once: true

- name: install npm packages grunt, bower, less
  npm: name={{ item }} global=yes
  with_items:
    - grunt
    - grunt-cli
    - bower
    - grunt-init
    - less
  run_once: true