---
##
# This is a python packages
##

- name: install python-dev and tools packages
  action: apt name=python-dev state=installed
  with_items:
    - python-setuptools
    - python-crypto
    - python-pip
    - build-essential
    - openssh-server
    - python-imaging
    - ipython
    - python-docutils
    - python-software-properties
    - python-mapscript
    - bash-completion
  run_once: true
  notify:
    - pip upgmcrade setuptools

- name: update bashrc PYTHONPATH
  lineinfile:
    dest=/home/{{ project }}{{ team_user_prefix }}/.bashrc
    line="export PYTHONPATH=.:..:../lib"
  run_once: true