---
#- service: name=httpd state=stopped  # stop a service, can also use notify: service stop
- name: make fs
  filesystem: fstype=ext4 dev="{{ home_vol }}"
  run_once: true
- name: create directory for mount
  file: path="{{ home_vol_mount }}"
- name: mount the new fs
  mount: name="{{ home_vol_mount }}" src="{{ home_vol }}" fstype=ext4 state=mounted #present
- name: copy files to new point
  shell: cp -r ~ {{ home_vol_mount }}
- name: create symlink in home dir called "link"
  file: dest=~/link src="{{ home_vol_mount }}" state=link force=yes
  sudo: false