---
#- name: Get instance information
#  debug:
#    msg: "{{ instance_values }}"

- name: create new ec2 instance
  ec2:
    region: "{{ awsec2_defaults.aws_region }}"
    zone: "{{ awsec2_defaults.aws_zone }}"
    keypair: "{{ awsec2_defaults.aws_key_pair }}"
    group: "{{ awsec2_defaults.security_group }}"
    instance_type: "{{ awsec2_defaults.instance_type }}"
    image: "{{ awsec2_defaults.ami_id }}"
    count: 1
    wait: yes
    instance_tags:
      Name: "{{ server_name }}"
  register: ec2_info

- name: wait for instances to listen on port 22
  wait_for:
    state: started
    host: "{{ ec2_info.instances[0].public_dns_name }}"
    port: 22
  when: ec2_info|changed

#- name: add new instance to ec2hosts group memory inventory
#  add_host:
#    hostname: "{{ ec2_info.instances[0].public_ip }}"
#    groupname: ec2hosts
#    instance_id: "{{ ec2_info.instances[0].id }}"
#  when: ec2_info|changed

- name: associate new elastic IPs with (each of) the instance(s)
  ec2_eip: "instance_id={{ item }} region={{ awsec2_defaults.aws_region }}"
  with_items: ec2_info.instance_ids
  register: elastic_ip

- name: get ec2_info information
  debug:
    msg: "{{ ec2_info }}"

- name: output the elastic IP
  debug: msg="Allocated IP is {{ elastic_ip }}"


