---
#- name: Print
#  debug: msg="{{ item.0.name }} {{ item.1.name }}"
#  #with_items: ebs_volumes
#  with_nested:
#    - ebs_volumes
#    - ebs_volumes

- name: create new ec2 instance
  ec2:
    region: "{{ aws_defaults.aws_region }}"
    zone: "{{ aws_defaults.aws_zone }}"
    keypair: "{{ aws_defaults.aws_key_pair }}"
    group: "{{ aws_defaults.security_group }}"
    instance_type: "{{ aws_defaults.instance_type }}"
    image: "{{ aws_defaults.ami_id }}"
    count: 1
    wait: yes
    instance_tags:
      Name: "{{ server_name }}"
  register: ec2_info

#- name: Print
#  debug: msg="{{ item.1.id }} {{ item.0.name }} {{ item.0.size }} {{ item.0.device }} {{ item.0.volume_type }}"
#  with_nested:
#    - ebs_volumes
#    - ec2_info.instances

#- name: add new instance to ec2hosts group memory inventory
#  add_host:
#    hostname: "{{ ec2_info.instances[0].public_ip }}"
#    groupname: ec2hosts
#    instance_id: "{{ ec2_info.instances[0].id }}"
#  when: ec2_info|changed

