---
- name: wait for instances to listen on port 22
  wait_for:
    state: started
    host: "{{ ec2_info.instances[0].public_dns_name }}"
    port: 22
  when: ec2_info|changed

#- name: add new instance to ec2hosts group memory inventory
#  add_host:
#    hostname: "{{ ec2_info.instances[0].public_ip }}"
#    groupname: ec2hosts
#    instance_id: "{{ ec2_info.instances[0].id }}"
#  when: ec2_info|changed

