---
- name: wait for instances to listen on port 22
  wait_for:
    state: started
    host: "{{ ec2_info.instances[0].public_dns_name }}"
    port: 22
    delay: 300 # wait 5 mins for instance to become ready to provision
  when: ec2_info|changed
